# Their are some python libaris
> Numpy, Scipy, Pandas, Scikt-learn, Matplotlib, Seaborn, Plotly.

1. NumPy: This is a short form of numerical Python. It is the most powerful scientific library available in Python for handling multidimensional arrays, matrices, and methods in order to compute mathematics efficiently.


2. SciPy: This is also a powerful scientific computing library for performing scientific, mathematical, and engineering operations.


3. Pandas: This is a data exploration and manipulation library that offers tabular data structures such as DataFrames and various methods for data analysis and manipulation.


4. Scikit-learn: This stands for "Scientific Toolkit for Machine learning". It is a machine learning library that offers a variety of supervised and unsupervised algorithms, such as regression, classification, dimensionality reduction, cluster analysis, and anomaly detection.


5. Matplotlib: This is a core data visualization library and is the base library for all other visualization libraries in Python. It offers 2D and 3D plots, graphs, charts, and figures for data exploration. It runs on top of NumPy and SciPy.


6. Seaborn: This is based on Matplotlib and offers easy to draw, high-level, interactive, and more organized plots.


7. Plotly: Plotly is a data visualization library. It offers high quality and interactive graphs, such as scatter charts, line charts, bar charts, histograms, boxplots, heatmaps, and subplots.

# PYTHON PACKAGES FOR PANDAS

In [87]:
import numpy as np
import pandas as pd


In [152]:
# Creating a Series by passing a list of values, letting pandas create a default integer index:

s = pd.Series([1,3,32,3,42, 4,7])
print(s)

0     1
1     3
2    32
3     3
4    42
5     4
6     4
7     7
dtype: int64


In [163]:
#Creating a DataFrame by passing a NumPy array, with a datetime index and labeled columns:

dates = pd.date_range("20220708", periods = 7)
print(dates)

df = pd.DataFrame(np.random.randn(7, 6), index=dates, columns=list("abcdef"))

print(df)

DatetimeIndex(['2022-07-08', '2022-07-09', '2022-07-10', '2022-07-11',
               '2022-07-12', '2022-07-13', '2022-07-14'],
              dtype='datetime64[ns]', freq='D')
                   a         b         c         d         e         f
2022-07-08  0.576587 -1.263870 -0.219578 -1.030446  0.172163  1.498818
2022-07-09 -0.332182  1.797082 -1.384102  0.848190  0.789702  0.303632
2022-07-10 -0.162132  0.934930  1.124216  0.375916  0.372137  0.528237
2022-07-11  0.574701 -1.853907 -0.588881  0.704618 -1.982407  1.025595
2022-07-12  0.667200  1.035017 -0.830396  1.021452  0.576320  0.705602
2022-07-13 -0.047203 -0.944950  0.670371  1.484633  1.000467 -1.790471
2022-07-14 -1.594445  2.520369  0.399168 -2.032648  2.447106 -1.297694


In [164]:
#Creating a DataFrame by passing a NumPy array, with a datetime index and labeled columns:

s = pd.Series([1,2,3,2,4, 5,6,7])

df = pd.DataFrame( (8, 6), index=s, columns=list("abcdef"))

print(df)

          a         b         c         d         e         f
1  0.998618  1.687498 -0.555126  2.524932  1.009462  0.030440
2  0.966386 -0.899722  1.215355  0.890602  0.714938  1.308230
3 -1.085193  0.243830  0.717682 -0.051641 -0.819642 -1.623812
2 -1.186979  1.811813  0.061928 -2.260935  0.956592 -0.591876
4 -0.344256  0.611057  1.657676 -2.132171  0.909590  0.237574
5 -0.284625 -0.273778 -0.520118 -0.639945 -0.556133 -0.532242
6  2.184476  1.310907 -0.166381 -0.462481 -0.597268  0.325540
7  1.000400  2.525346 -0.363334  1.418402 -0.848721  1.119074


In [155]:
#Creating a DataFrame by passing a dictionary of objects that can be converted into a series-like structure:

df2 = pd.DataFrame(
    {
        "A": 1,
        "B": pd.Timestamp("20210305"),
        "C": pd.Series(1, index = list(range(5)), dtype = "float32"),
        "D": np.array([67]* 5, dtype = "int32"),
        "E": "foo",
        "F": pd.Categorical(["test","train","tometo","rje","sdghgg"]),
    }
)
print(df2)

   A          B    C   D    E       F
0  1 2021-03-05  1.0  67  foo    test
1  1 2021-03-05  1.0  67  foo   train
2  1 2021-03-05  1.0  67  foo  tometo
3  1 2021-03-05  1.0  67  foo     rje
4  1 2021-03-05  1.0  67  foo  sdghgg


# Python.append() and .extend() Methods

The append() method adds a single element towards the end of a list.

> Example

In [1]:
# list.append( adds a single element to a list)

months = ['January', 'February','March']
months.append('April')

print(months)

['January', 'February', 'March', 'April']


In [72]:

"""
    When i used ".append()" methods then i input 1 valu.
    But when i input one or more valu then we used ".extend()" methods.
"""

x = [1, 2, 3]
x.append(4)         # add one valu.

print("X = ",x)

y = [1, 2, 3]
y.extend([4, 5])    # add two valus.

print("Y = ",y)

X =  [1, 2, 3, 4]
Y =  [1, 2, 3, 4, 5]


# The standard process of data analysis

1. Collecting Data: Collect and gather data from several sources.

2. Preprocessing Data: Filter, clean, and transform the data into the required format.

3. Analyzing and Finding Insights: Explore, describe, and visualize the data and find insights and conclusions.

4. Insights Interpretations: Understand the insights and find the impact each variable has on the system.

5. Storytelling: Communicate your results in the form of a story so that a layman can understand them.

# The KDD process
    Knowledge Discovery From data.
    Knowledge Discovery in Databases.

1. ata Cleaning: 
In this first phase, data is preprocessed. Here, noise is removed, missing values are handled, and outliers are detected.

2. Data Integration:
In this phase, data from different sources is combined and integrated together using data migration and ETL tools.

3. Data Selection: 
In this phase, relevant data for the analysis task is recollected.

4. Data Transformation: In this phase, data is engineered in the required appropriate form for analysis.

5. Data Mining: In this phase, data mining techniques are used to discover useful and unknown patterns.

6. Pattern Evaluation: In this phase, the extracted patterns are evaluated.

7. Knowledge Presentation: After pattern evaluation, the extracted knowledge needs to be visualized and presented to business people for decision-making purposes.                                                    

#  Python Built in Modules

#### There are some Modules here.
###### 1. OS Modules.
###### 2. Sys Modules.
###### 3. Math Modules.
###### 4. Statistics Modules.
###### 5. Collections Modules.
###### 6. Random Modules.

## 3. Math Modules

> # numpy library

>The nump arra attributes

In [12]:
import numpy

print(numpy)


<module 'numpy' from 'C:\\Users\\rokon\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>


In [29]:
# Exmple of "numpy" library


import numpy as np
a = np.arange(15).reshape(3, 5)
print(a)

print("\n")

print(a.shape)

print("\n")

print(a.ndim)

print("\n")

print(a.dtype.name)

print("\n")

print(a.itemsize)

print("\n")

print(a.size)

print("\n")

print(type(a))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


(3, 5)


2


int32


4


15


<class 'numpy.ndarray'>


In [14]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
print(c)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [10]:
# Import `numpy` as `np`
import numpy as np
 
# Make the array `my_array`
my_array = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)

# Print `my_array`
print(my_array)

[[1 2 3 4]
 [5 6 7 8]]


In [13]:
from numpy import *
b = np.array([6, 7, 8], dtype = int64)
print(b)

print(type(b))
a = b

print(a)

[6 7 8]
<class 'numpy.ndarray'>
[6 7 8]


## 6. Random Modules




In [47]:
# Generate Random Floats

import random
random.random()

0.9135212432222998

In [19]:
# Generate Random Integers

import random
random.randint(1, 20)

10

In [22]:
# import random
import random
  
# prints a random value from the list
list1 = [1, 2, 3, 4, 5, 6]
print(random.choice(list1))

5


In [35]:
# import random
import random

random.seed(.0)

random.random()


0.8444218515250481

In [36]:
# randint() function
  
# import random module
import random
  
# Generates a random number between
# a given positive range
r1 = random.randint(5, 15)
print("Random number between 5 and 15 is % s" % (r1))
  
# Generates a random number between
# two given negative range
r2 = random.randint(-10, -2)
print("Random number between -10 and -2 is % d" % (r2))

Random number between 5 and 15 is 11
Random number between -10 and -2 is -10


# The "random.shiffle()" Elements Randomly

In [40]:
import random

r1 = [13,32,321,11,33,3]
print(random.shiffle(r1))

AttributeError: module 'random' has no attribute 'shiffle'

In [44]:
# Select Random Elements

import random
random.choice('computer')
          

random.choice([12,23,45,67,65,43])    
                                    # ei dui vabei data input deya jay..
random.choice((12,23,45,67,65,43))


43

In [46]:
# Genaret Random number.

import random

li = []
for i in range(10):
    li.append(random.randint(1,9))
print(li)

[1, 7, 5, 4, 9, 2, 5, 9, 5, 3]


In [106]:
# Shuffle Elements Randomly

numbers = [1, 2, 3, 4, 5]
random.shuffle(numbers)

print(numbers)

[4, 3, 2, 5, 1]


# Show screen resolution 

In [8]:
#Show Screen Resolution...

from win32api import GetSystemMetrics


width = GetSystemMetrics(0)
height = GetSystemMetrics(1)

print(width, height)




1366 768


# Show a pictur

In [38]:
#This program ran by Pycharm.

import cv2

path = r'C:\Users\rokon\Desktop\roko.png'


img = cv2.imread(path,0)
cv2.imshow('My_pictur', img)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.getWindowImageRect('ROkon')
# cv2.imwrite('new.png',img)

ModuleNotFoundError: No module named 'cv2'

In [40]:
import threading
  
def gfg():
    print("GeeksforGeeks\n")
  
timer = threading.Timer(10, gfg)
timer.start()
print("Cancelling timer\n")
timer.cancel()
print("Exit\n")

Cancelling timer

Exit



# Frequency
>dict, defaultdict, Counter

In [120]:
import random

def frequency_counter(li):
    freq_dt = dict()
    for item in li:
        if item in freq_dt:
            freq_dt[item] += 1
        else:
            freq_dt[item] = 1
    print(freq_dt)

if __name__ == "__main__":
    li = [7, 3, 9, 9, 8, 2, 7, 8, 6, 3, 8, 5, 8, 5, 6, 6, 2, 9, 1, 1]
    frequency_counter(li)


{7: 2, 3: 2, 9: 3, 8: 4, 2: 2, 6: 3, 5: 2, 1: 2}


In [3]:
import os
os.getcwd()

'C:\\Users\\rokon'

In [4]:
os.getcwd()

'C:\\Users\\rokon'

In [124]:
os.mkdir('C:\\Users\\rokon\\new')

In [125]:
os.getcwd()

'C:\\Users\\rokon'